### PR TITLE
chore: update spore-graphql to support searching compatible spore nft

### PR DESCRIPTION
**Pull request by ashuralyk**
# Description
considering `spore-graphql` bumped to v0.1.7, which supports searching compatible spore nfts, so it's essential to make demo support this too

### CODE REVIEW

**Comment by ashuralyk** [comment]
@ShookLyngs  please have a check

**Review by ShookLyngs — APPROVED** [review]
V1 spores are visible now.

**Comment by ashuralyk** [comment]
> V1 spores are visible now.

so, demo will be auto deployed after merging?

**Comment by ShookLyngs** [comment]
> so, demo will be auto deployed after merging?

Yes, you can check deployment info here: https://vercel.com/sporeprotocol/spore-demo

**Pull request merged**
